// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9aGL2ok6H-I0WZxvWIzzqn96gsY6WH7Y',
    appId: '1:399854494946:android:e46ae6494c01cdc2aa6abb',
    messagingSenderId: '399854494946',
    projectId: 'codewarriors-7c18e',
    databaseURL: 'https://codewarriors-7c18e.firebaseio.com',
    storageBucket: 'codewarriors-7c18e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHR79GYtsbfqKB1U4RWaWTE5oygcz16dM',
    appId: '1:399854494946:ios:fed8cb3abae783bdaa6abb',
    messagingSenderId: '399854494946',
    projectId: 'codewarriors-7c18e',
    databaseURL: 'https://codewarriors-7c18e.firebaseio.com',
    storageBucket: 'codewarriors-7c18e.appspot.com',
    androidClientId: '399854494946-65k830vjccriv5metklqf9oaq2eh9ekr.apps.googleusercontent.com',
    iosClientId: '399854494946-r45lnq3snvpf315k30shrj3aohfm1uip.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeWarrior',
  );
}
